### ISSUE TITLE
Extreme distortion

### ISSUE THREAD

**Issue by ntonnaett** [brummer10/GxCreamMachine.lv2#1]
I don't get any clean sound out of the CreamMachine. If the input level is extremely low I get a clue what it might sound. But I think there's something wrong with the levels at some point.

**Comment by brummer10** [comment]
Hi

Thanks for your report.
Do you using it with your bass?
Do you using the MOD version or the linux version?

However, you may play with the distortion level when editing the file 
dsp/12ax7_table.h line 23
https://github.com/brummer10/GxCreamMachine.lv2/blob/master/dsp/12ax7_table.h#L23

reducing the istep value will reduce the overall gain and distortion. 
the line consists of low, high, istep, size.
So the third value needs to be reduced. Maybe try 33.333

If you found a value which satisfy your needs, let me know, maybe I could add a selector for this in the UI, as I like it how it is.

**Comment by ntonnaett** [comment]
I'm using my guitar directly plugged into a focusrite scarlett 2i4. Bootstrapping for mod duo doesn't work for me at the moment.
Reducing the istep value sounds a lot more what I expected. Could you record an example how it sounds for you? There's also something like a hiss when I'm playing. I just don't know what to expect. I thought it would be a more subtle effect.

**Comment by brummer10** [comment]
Which samplerate do you use?

**Comment by ntonnaett** [comment]
I used 44.1 kHz. I will try with 48 kHz.

**Comment by brummer10** [comment]
Yes, try that, as this plug is supposed to work best with 48kHz which we use on the MOD.
