### ISSUE TITLE
Disable cab sim

### ISSUE THREAD

**Issue by apclement** [brummer10/GxCreamMachine.lv2#3]
Hi, is it possible to bypass the cab sim stage ? I would like to use IR instead for that.
Thanks !

**Comment by brummer10** [comment]
Hi
Sorry, but that is not possible. The "cabinet simulation" is a simulation of a direct out port of the amp, and deep bounded into the source, and is important for the overall sound of the plug. 
You could use any IR in addition to it. 

regards
hermann

**Comment by apclement** [comment]
Ok thanks. By the way the CreamMachine sounds very well, perfect for a beautiful lead sound...
Thank you for all your great work !

**Comment by brummer10** [comment]
I'm glad you like it nevertheless. 
Close now.
